# Generated by Django 2.1.5 on 2023-03-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
