# Generated by Django 2.1.5 on 2023-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20230301_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
