# Generated by Django 2.1.5 on 2023-03-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_comments_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
